### ISSUE TITLE
我用 Vue 实现了一遍，是否可以放一个链接到该项目中！

### ISSUE THREAD

**Issue by yejimeiming** [027xiguapi/pear-rec#142]
感谢作者开源这个项目，因为个人业务需求用 Vue3 实现了一遍该项目的“截屏功能”，如果作者愿意，我愿意将代码再次开源出来。
我只是希望作者能给个链接位置指引到我的 Vue3 版本的项目上。

**Comment by 027xiguapi** [comment]
可以，你提交 PR 吧
