### ISSUE TITLE
跨平台

### ISSUE THREAD

**Issue by WHMyyds** [027xiguapi/pear-rec#166]
希望作者尽快出Linux版本，谢谢。我急需一个Linux版的录屏软件🙏

**Comment by 027xiguapi** [comment]
你需要什么版本？
我们现在有[AppImage](https://github.com/027xiguapi/pear-rec/releases/download/v1.3.15/pear-rec-Linux-1.3.15.AppImage)
![image](https://github.com/027xiguapi/pear-rec/assets/31228055/c49efe5f-38b3-40f3-8fd8-4219fcbeec85)

**Comment by WHMyyds** [comment]
好吧，我没看见🙃
在我发这条issue时，还没有Linux版本
大佬失敬
