### ISSUE TITLE
what's node version

### ISSUE THREAD

**Issue by binbin0915** [027xiguapi/pear-rec#17]
RT

**Comment by 027xiguapi** [comment]
node: v18.14.2,
pnpm: v8.7.5

![image](https://github.com/027xiguapi/pear-rec/assets/31228055/5b1bf3f7-dc79-4fc9-831f-5669aa1dbfaa)

**Comment by 027xiguapi** [comment]
https://github.com/WiseLibs/better-sqlite3/issues/704
