### ISSUE TITLE
打开pear-rec闪退

### ISSUE THREAD

**Issue by Wardon-Binghan** [027xiguapi/pear-rec#77]
OS:Win10 19045
打开pear-rec闪退,安装所有运行库也无法运行。

**Comment by 027xiguapi** [comment]
你的软件是什么版本？有具体的报错原因吗？用管理员启动试一试

**Comment by 027xiguapi** [comment]
参考:  https://stackoverflow.com/questions/68874940/gpu-process-isnt-usable-goodbye
